// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN4Q3GeOBGSXTetUFhhwx9eyAJk7KzL1A',
    appId: '1:340804707686:web:6de49f6cbcdc4e77ddd4a7',
    messagingSenderId: '340804707686',
    projectId: 'flutter-chat-app-5eef4',
    authDomain: 'flutter-chat-app-5eef4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5eef4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHnZbhSMmUGiy48DyD03jtBtgZQQ_WKbo',
    appId: '1:340804707686:android:29cf2982f4cecaa8ddd4a7',
    messagingSenderId: '340804707686',
    projectId: 'flutter-chat-app-5eef4',
    storageBucket: 'flutter-chat-app-5eef4.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN4Q3GeOBGSXTetUFhhwx9eyAJk7KzL1A',
    appId: '1:340804707686:web:160ece56bf57b5abddd4a7',
    messagingSenderId: '340804707686',
    projectId: 'flutter-chat-app-5eef4',
    authDomain: 'flutter-chat-app-5eef4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-5eef4.appspot.com',
  );

}